# Site settings
title: "Chinmay Singh"
description: "Another backend dev."
author: "Chinmay Singh"
name: "Chinmay Singh"

# Site URL configuration
url: "https://chinmaysingh.me"
baseurl: ""

# Social media profiles
social:
  github: "SinghChinmayy"
  linkedin: "singhchinmay"
# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-archives

jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: category
    tag: tag
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'

# Defaults
# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - .git/
  - .github/

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge